name: Build iOS unsigned IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios-unsigned:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sanity macOS
        run: |
          sw_vers
          xcodebuild -version
          which node || true
          which pod || true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
      - name: Expo prebuild (iOS)
        env:
          EXPO_NO_INTERACTIVE: '1'
          CI: 'true'
        run: |
          npx --yes expo prebuild -p ios --non-interactive --no-install
      - name: Install CocoaPods and dependencies
        run: |
          if ! gem list cocoapods -i > /dev/null 2>&1; then
            sudo gem install cocoapods --no-document
          fi
          cd ios
          pod repo update
          pod install
      - name: Verify .xcworkspace
        run: |
          test -f ios/*.xcworkspace/contents.xcworkspacedata
      - name: Discover workspace and scheme
        id: discover
        shell: bash
        working-directory: ios
        run: |
          set -euo pipefail
          WORKSPACE=$(ls *.xcworkspace | head -n1)
          echo "workspace=$WORKSPACE" >> $GITHUB_OUTPUT
          SCHEME=$(xcodebuild -workspace "$WORKSPACE" -list -json | /usr/bin/python3 -c "import sys,json; d=json.load(sys.stdin); w=d.get('workspace') or {}; s=w.get('schemes') or []; print(s[0] if s else '')")
          if [ -z "$SCHEME" ]; then echo 'No scheme found' && exit 1; fi
          echo "scheme=$SCHEME" >> $GITHUB_OUTPUT
      - name: Build unsigned .app
        working-directory: ios
        run: |
          xcodebuild \
            -workspace "${{ steps.discover.outputs.workspace }}" \
            -scheme "${{ steps.discover.outputs.scheme }}" \
            -configuration Release \
            -sdk iphoneos \
            -arch arm64 \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath ../build
      - name: Package unsigned IPA
        shell: bash
        run: |
          APP_PATH=$(find build -type d -name "*.app" | head -n1)
          if [ -z "$APP_PATH" ]; then echo 'App not found' && exit 1; fi
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -qry ios-todo-unsigned.ipa Payload
          rm -rf Payload
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-todo-unsigned-ipa
          path: ios-todo-unsigned.ipa

