name: Build iOS unsigned IPA

on:
  workflow_dispatch:

jobs:
  build-ios-unsigned:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Prebuild iOS project (Expo)
        env:
          EXPO_NO_INTERACTIVE: '1'
          EXPO_OFFLINE: '1'
        run: |
          npx --yes expo prebuild -p ios --non-interactive --no-install

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods --no-document
          cd ios
          pod install --repo-update

      - name: Discover workspace and scheme
        id: discover
        shell: bash
        run: |
          WORKSPACE=$(ls -1 ios/*.xcworkspace | head -n1)
          echo "workspace=$WORKSPACE" >> $GITHUB_OUTPUT
          # Extract first scheme via xcodebuild JSON
          SCHEME=$(xcodebuild -workspace "$WORKSPACE" -list -json | /usr/bin/python3 - <<'PY'
import json,sys
data=json.load(sys.stdin)
schemes=(data.get('workspace',{}) or {}).get('schemes') or []
print(schemes[0] if schemes else '')
PY
          )
          if [ -z "$SCHEME" ]; then echo 'No scheme found' && exit 1; fi
          echo "scheme=$SCHEME" >> $GITHUB_OUTPUT
          echo "Workspace: $WORKSPACE"
          echo "Scheme: $SCHEME"

      - name: Build unsigned .app
        run: |
          xcodebuild \
            -workspace "${{ steps.discover.outputs.workspace }}" \
            -scheme "${{ steps.discover.outputs.scheme }}" \
            -configuration Release \
            -sdk iphoneos \
            -arch arm64 \
            CODE_SIGNING_ALLOWED=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            -derivedDataPath build
        env:
          NSUnbufferedIO: 'YES'

      - name: Package unsigned IPA
        shell: bash
        run: |
          APP_PATH=$(find build -type d -name "*.app" | head -n1)
          if [ -z "$APP_PATH" ]; then echo 'App not found' && exit 1; fi
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -qry ios-todo-unsigned.ipa Payload
          rm -rf Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-todo-unsigned-ipa
          path: ios-todo-unsigned.ipa
