name: Build iOS unsigned IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios-unsigned:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sanity macOS
        run: |
          sw_vers
          xcodebuild -version
          which node || true
          which pod || true

